import matplotlib.pyplot as plt
import numpy as np

loss1 = np.loadtxt("loss_1_GD.csv")
accuracy1 = np.loadtxt("accuracy_1_GD.csv")
loss2 = np.loadtxt("loss_2_GD.csv")
accuracy2 = np.loadtxt("accuracy_2_GD.csv")
loss3 = np.loadtxt("loss_3_GD.csv")
accuracy3 = np.loadtxt("accuracy_3_GD.csv")
loss4 = np.loadtxt("loss_4_GD.csv")
accuracy4 = np.loadtxt("accuracy_4_GD.csv")

loss5 = np.loadtxt("loss_5_GD.csv")
accuracy5 = np.loadtxt("accuracy_5_GD.csv")

plt.figure(figsize=(8, 7))
plt.subplot(1, 2, 1)
plt.plot(loss1, label="1", linewidth=1)
plt.plot(loss2, label="2", linewidth=1)
plt.plot(loss3, label="3", linewidth=1)
plt.plot(loss4, label="4", linewidth=1)
plt.plot(loss5, label="5", linewidth=1)
#plt.title("Train Loss with Varying Batch Sizes")
plt.title("Train Loss with Varying Subclients")
plt.legend(loc='upper right', prop={'size': 10}, ncol=2, title="Number of subclients")
#plt.ylim([0,1.5])
plt.ylabel('Training Loss')
plt.xlabel('Global rounds')

plt.subplot(1, 2, 2)
plt.plot(accuracy1, label="1", linewidth=1)
plt.plot(accuracy2, label="2", linewidth=1)
plt.plot(accuracy3, label="3", linewidth=1)
plt.plot(accuracy4, label="4", linewidth=1)
plt.plot(accuracy5, label="5", linewidth=1)
#plt.title("Test Accuracy with Varying Batch Sizes")
plt.title("Train Loss with Varying Subclients")
plt.legend(loc='lower right', prop={'size': 10}, ncol=2, title="Number of subclients")
plt.ylim([0,1])
plt.ylabel('Testing Acc')
plt.xlabel('Global rounds')
plt.show()
